apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apache-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sanyakarbyrator/task26
    path: 'nginx_chart'        
    targetRevision: HEAD
    helm:
      valueFiles:
        - values_apache.yml       
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true