apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agro
  namespace: argocd
spec:
  project: default
  
  source:
    repoURL: https://github.com/sanyakarbyrator/task26
    reegetRevision: HEAD
    path: "apps"


  destination:
    server: https://kubernetes.default.svc
    namespace: default
    helm:
      valuesFile:
      - values.yml
     

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true