{{- if .Values.enablesecrets }}
{{- range .Values.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
type: {{ .type }}
stringData:
{{- range .secrets }}
  {{ .secname }}: |
{{ .value | indent 4 }}
{{- end }}

{{- end }}
{{- end }}

